app = 'go-hire-back'
primary_region = 'eze'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/health"
    protocol = "http"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1