export enum NotificationType {
  OFFER_JOB = 'OFFER_JOB',
  ACEPTED_JOB = 'ACEPTED_JOB',
  FINISHED = 'FINISHED',
  SEND_APPLY_REQUEST = 'SEND_APPLY_REQUEST',
  VIEWS_PROFILE = 'VIEWS_PROFILE',
  VIEWS_PUBLICATION = 'VIEWS_PUBLICATION',
}
